In [1]:
import pandas as pd
# import numpy as np

In [2]:
PATH = '../data/durecdial/'
df = pd.read_csv(PATH + 'train_sentence_small.csv')

In [55]:
def sucess_fail(df, show_question=True, show_fail = True, min_range=0, max_range=100):
    dfa = df[(df.recdial == 1)][['user_id', 'sentence_index', 'sentence', 'is_user', 'deny']].copy()
    cols = ['user_id', 'sentence_index', 'sentence', 'is_user']
    indices = dfa[(dfa.is_user == 1) & (dfa.deny == show_fail)].index.to_list()
    if show_question:
        new_indices = []
        for index in indices:
            new_indices.append(index-1)
            new_indices.append(index)
        return df.loc[new_indices][cols]
    else:
        return dfa.loc[indices][cols]

In [56]:
sucess_fail(df)

,user_id,sentence_index,sentence,is_user
9,0,9,Then you can watch Nicholas Tse's movie The St...,0
10,0,10,What kind of movie is it?,1
33,2,3,"Then I recommend that you listen to Change Me,...",0
34,2,4,"I‘ve heard it, and I'm not interested in this ...",1
51,3,7,I know a place which cooks Sautéed Spicy Pork ...,0
...,...,...,...,...
66744,4145,4,I don't want to hear this song for the time be...,1
66745,4145,5,How about Open Fire? It's a dynamic fast song ...,0
66746,4145,6,Its name sounds very stylish.,1
66761,4146,5,What about So Close So Far? It's an episode in...,0
66762,4146,6,How about this song?,1

## 이후 수정을 위한 테스트

In [48]:
dfb = df[(df.recdial == 1)][['user_id', 'goal_type', 'sentence_index', 'sentence', 'is_user', 'deny']].copy()
dfb

,user_id,goal_type,sentence_index,sentence,is_user,deny
7,0,Movie recommendation,7,Then don't miss her movie Failan. It shows a l...,0,False
8,0,Movie recommendation,8,"Although I really like her, I prefer to see Ni...",1,False
9,0,Movie recommendation,9,Then you can watch Nicholas Tse's movie The St...,0,False
10,0,Movie recommendation,10,What kind of movie is it?,1,True
11,0,Movie recommendation,11,"It's an action drama, with a little bit of thr...",0,False
...,...,...,...,...,...,...
66853,4152,Movie recommendation,13,Enjoy the movie.,0,False
66863,4153,Music recommendation,7,I'd like to recommend you his Spend Together. ...,0,False
66864,4153,Music recommendation,8,"Spending together seems ordinary and simple, b...",1,False
66865,4153,Music recommendation,9,You have a thorough understanding.,0,False
66866,4153,Music recommendation,10,Absolutely.,1,False

In [52]:
dfb[dfb.user_id == 1]

,user_id,goal_type,sentence_index,sentence,is_user,deny
19,1,Food recommendation,3,There's nothing I don't know. I also know that...,0,False
20,1,Food recommendation,4,"Okay, I like it.",1,False
21,1,Food recommendation,5,I know a restaurant where the Marinated Fish i...,0,False
22,1,Food recommendation,6,"Woah, there's grouper! I really like it! It's ...",1,False
23,1,POI recommendation,7,"If you like it so much, I know a restaurant wh...",0,False
24,1,POI recommendation,8,Then tell me about the average meal cost per p...,1,False
25,1,POI recommendation,9,It costs 0 yuan per person. The address is the...,0,True
26,1,POI recommendation,10,Okay. I'll be there tomorrow noon with my part...,1,False
27,1,POI recommendation,11,"Okay, I'll make a reservation for you. I'll sa...",0,False

In [54]:
dfb[dfb.user_id == 1].sentence.iloc[4]

'If you like it so much, I know a restaurant which cooks groupers very well. Mr.Fish Roasted. The Marinated Fish here is very authentic!'