In [1]:
import json, pandas as pd
import numpy as np

In [2]:
dev = pd.read_csv('./dev.csv')
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [44]:
train.columns

Index(['goal', 'conversation', 'goal_topic_list', 'goal_type_list',
       'situation', 'knowledge', 'user_profile_age_range', 'user_profile_name',
       'user_profile_residence', 'user_profile_accepted_food',
       'user_profile_accepted_movies', 'user_profile_accepted_music',
       'user_profile_rejected_music', 'user_profile_gender',
       'user_profile_accepted_celebrities', 'user_profile_accepted_movie',
       'user_profile_reject', 'user_profile_rejected_movies',
       'user_profile_occupation', 'user_profile_accepted_music.1',
       'user_profile_accepted_poi', 'user_profile_favorite_news',
       'user_profile_accepted_news', 'user_profile_poi'],
      dtype='object')

In [30]:
train.user_profile_accepted_movie

0       ['The Legend of Speed']
1                           NaN
2                   Flash Point
3            ['Battle of Wits']
4                           NaN
                 ...
5673        ["Nana's Rose war"]
5674          ["No Man's Land"]
5675                  ['Reset']
5676            ['Three Times']
5677           Running On Karma
Name: user_profile_accepted_movie, Length: 5678, dtype: object

In [191]:
# train.user_profile_name.value_counts()
train.user_profile_accepted_movie

0       ['The Legend of Speed']
0       ['The Legend of Speed']
0       ['The Legend of Speed']
0       ['The Legend of Speed']
0       ['The Legend of Speed']
                 ...
5677           Running On Karma
5677           Running On Karma
5677           Running On Karma
5677           Running On Karma
5677           Running On Karma
Name: user_profile_accepted_movie, Length: 130710, dtype: object

> 여러 Feature에 List가 포함되어 있는 것을 확인할 수 있다.

In [46]:
train

,goal,conversation,goal_topic_list,goal_type_list,situation,knowledge,user_profile_age_range,user_profile_name,user_profile_residence,user_profile_accepted_food,...,user_profile_accepted_celebrities,user_profile_accepted_movie,user_profile_reject,user_profile_rejected_movies,user_profile_occupation,user_profile_accepted_music.1,user_profile_accepted_poi,user_profile_favorite_news,user_profile_accepted_news,user_profile_poi
0,[1] Q&A(Cecilia Cheung)-->[2] Chat about stars...,['[1] Who is the leading actor of the movie Le...,"['Left Right Love Destiny', 'Left Right Love D...","['Q&A', 'Q&A', 'Q&A', 'Chat about stars', 'Cha...","Time: 12:00, at school","[['Cecilia Cheung', 'Stars', 'Left Right Love ...",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,...,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],['News'],"['Everyday is Valentine', 'Unforgettable', 'Ki...",Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN
1,[1]Ask about weather-->[2] Food recommendation...,"['[1] Baby, can you tell me the weather today?...","['Ask about weather', 'Ask about weather', 'As...","['Ask about weather', 'Ask about weather', 'As...","Time: 20 18 - 12 - 12 22:00, at home Wedne...","[['Hengshui', '2018-12-12', 'Sunny with southw...",Under 18 years old,Mingzheng Li,Hengshui,Marinated Fish,...,['Jacky Cheung'],NaN,['Movie'],NaN,Student,['Wolf Legend'],Mr.Fish Roasted,"[""Jacky Cheung's news""]",NaN,NaN
2,[1] Music on demand(Hand in Hand)-->[2] Music ...,"[""[1] Let's listen to Hand in Hand."", ""It's pl...","['Hand in Hand', 'Hand in Hand', 'Hand in Hand...","['Music on demand', 'Music on demand', 'Music ...","Time: 18:00,on the way home","[[], [], ['Leehom Wang', 'Sings', 'Hand in Han...",Over 50 years old,Li Xu,Yangzhou,Marinated Fish,...,"['Bingbing Fan', 'Leehom Wang']",Flash Point,['Poi'],"['Lust, Caution']",Employed,['Hand in Hand'],NaN,"[""Bingbing Fan's news"", ""Leehom Wang's news""]",NaN,NaN
3,[1]Ask about weather-->[2] Food recommendation...,"[""[1] Good afternoon. What's the weather like ...","['Ask about weather', 'Ask about weather', 'As...","['Ask about weather', 'Ask about weather', 'As...","Time: 20 18 - 11 - 22 12:00, at school Thu...","[['Xining', '2018-11-22', 'Sunny with northwes...",26-35,Jiaoyang Jin,Xining,Sautéed Spicy Pork,...,['Bingbing Fan'],['Battle of Wits'],['music'],['Ever Since We Love'],Student,NaN,Laoqi Sichuan Restaurant,"[""Bingbing Fan's news""]",NaN,NaN
4,[1]Greetings-->[2]Ask about user's name-->[3]A...,"['[1] Good evening. What are you doing?', ""Hel...","['Greetings', 'Greetings', 'Greetings', 'Greet...","['Greetings', 'Greetings', 'Greetings', 'Greet...","Time: 20:00, at home Topic: Academic setback","[[], [], [], [], [], [], [], [], [], [], ['Xin...",7-10,Xinxi Zhang,Shijiazhuang,NaN,...,NaN,NaN,NaN,NaN,Student,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5673,[1] Q&A(Na Xie)-->[2] Chat about stars(Na Xie)...,"[""[1] What 's Na Xie's height?"", 'Hello, Na X...","['Na Xie', 'Na Xie', 'Na Xie', 'Na Xie', 'Na X...","['Q&A', 'Q&A', 'Q&A', 'Chat about stars', 'Cha...",Time: 7:00,"[['Na Xie', 'Height', '166cm'], ['Na Xie', 'He...",Over 50 years old,Pinglu Liu,Kunming,poached spicy slices of pork,...,"['Na Xie', 'Jiong He']","[""Nana's Rose war""]",['News'],"[""Nana's War""]",Retired,Little Love,['Yicaiyige Classic Sichuan Dishes(Qicai Me To...,NaN,NaN,NaN
5674,[1]Ask about weather-->[2] Food recommendation...,"[""[1] Hi, how's the weather today?"", ""The weat...","['Ask about weather', 'Ask about weather', 'As...","['Ask about weather', 'Ask about weather', 'As...","Time: 20 18 - 10 - 13 22:00, at home Saturday","[['Shanghai', '2018-10-13', 'Mostly cloudy wit...",Over 50 years old,Qinan He,Shanghai,Chicken Feet with Pickled Peppers,...,"['Bo Huang', 'Jiong He']","[""No Man's Land""]",['Poi'],"['Happy Running', 'Crazy Racer']",Employed,['Those Years'],NaN,NaN,Bo Huang's news; Jiong He's news,NaN
5675,[1] Q&A(Mi Yang)-->[2] Chat about stars(Mi Yan...,"['[1] Who is the star of Perfect Two?', 'Yang ...","['Perfect Two', 'Perfect Two', 'Perfect Two', ...","['Q&A', 'Q&A', 'Q&A', 'Chat about stars', 'Cha...","Time: 20:00, at home","[['Mi Yang', 'Stars', 'Perfect Two'], ['Mi Yan...",Over 50 years old,Xiaofeng Niu,Chengdu,Kung Pao Chicken,...,"['Mi Yang', 'Leehom Wang']",['Reset'],['Poi'],"[""All's Well, Ends Well 2012""]",Employed,['The Sun Washed by Spring Rain'],NaN,NaN,Mi Yang's news; Leehom Wang's news,NaN
5676,[1]Greetings-->[2]Ask about user's name-->[3]A...,"['[1] Good morning.', 'Good afternoon!', 'What...","['Greetings', 'Greetings', 'Greetings', 'Greet...","['Greetings', 'Greetings', 'Greetings', 'Greet...","Time: 7:00, on the way to school Topic: Doing ...","[[], [], [], [], [], [], [], [], [], [], ['Jia...",18-25,Jiaoqian Yang,Xuzhou,Yu-Shiang Shredded Pork (Sautéed with Spicy Ga...,...,"['Hsu Chi', 'Kris Wu']",['Three Times'],['Poi'],[],Student,['Heaven & Earth'],NaN,NaN,Hsu Chi's news; Kris Wu's news,NaN
5677,[1] Q&A(Leslie Cheung)-->[2] Chat about stars(...,"['[1] Hi, do you know what sign Leslie Cheung ...","['Leslie Cheung', 'Leslie Cheung', 'Leslie Che...","['Q&A', 'Q&A', 'Q&A', 'Chat about stars', 'Cha...","Time: 12:00, at school","[['Leslie Cheung', 'Star sign', 'Virgo'], ['Le...",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,...,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,['Poi'],['The Kid'],Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN

### Column to DataFrame
> 여러 값을 포함하는 feature의 값들을 여러 행으로 분리하기

In [47]:
temp_sentence = train.conversation.apply(lambda x:pd.Series(x.split(',')))
temp_goal_topic = train.goal_topic_list.apply(lambda x:pd.Series(x.split(',')))
temp_goal_type = train.goal_type_list.apply(lambda x:pd.Series(x.split(',')))
temp_knowledge = train.knowledge.apply(lambda x:pd.Series(x.split(']')))
temp_sentence.shape, temp_goal_topic.shape, temp_goal_type.shape, temp_knowledge.shape

((5678, 51), (5678, 38), (5678, 28), (5678, 30))

> 각 feature의 List들을 열로 바꿔줌으로써 Feature별 dataframe이 생성된다.

In [48]:
temp_knowledge

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,"[['Cecilia Cheung', 'Stars', 'Left Right Love ...",", ['Cecilia Cheung', 'Stars', 'Left Right Love...",", [",", ['Cecilia Cheung', 'Intro', 'Chinese dreamgirl'",", [",", ['Cecilia Cheung', 'Achievement', 'Outstandi...",", [",", ['Failan', 'Comments', ""Failan presents a lo...",", [",", ['Nicholas Tse', 'Stars', 'The Stool Pigeon'",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[['Hengshui', '2018-12-12', 'Sunny with southw...",", ['Hengshui', '2018-12-12', 'Sunny with south...",", [",", ['Sunny with southwest winds. The high will ...",", [",", ['Marinated Fish', 'Ingredients', 'grouper、O...",", [",", ['Mr.Fish Roasted', 'Specials', 'Marinated F...",", ['Mr.Fish Roasted', 'Rating', '5'",", ['Mr.Fish Roasted', 'Rating', '5'",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[[,", [",", ['Leehom Wang', 'Sings', 'Hand in Hand'",", ['Leehom Wang', 'Sings', 'Change Me'",", [",", ['Leehom Wang', 'Sings', 'All the Things You...",", [",", [",", [",", [",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[['Xining', '2018-11-22', 'Sunny with northwes...",", ['Xining', '2018-11-22', 'Sunny with northwe...",", [",", ['Sunny with northwest winds. The high will ...",", [",", ['Sautéed\xa0Spicy\xa0Pork\xa0', 'Type', 'Ho...",", [",", ['Laoqi Sichuan Restaurant', 'Specials', 'Sa...",", ['Laoqi Sichuan Restaurant', 'Price per pers...",", ['Laoqi Sichuan Restaurant', 'Price per pers...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[[,", [",", [",", [",", [",", [",", [",", [",", [",", [",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5673,"[['Na Xie', 'Height', '166cm'",", ['Na Xie', 'Height', '166cm'",", [",", ['Na Xie', 'Intro', 'beautiful hostess'",", [",", ['Na Xie', 'Achievement', 'Golden Eagle Awar...",", [",", ['Na Xie', 'Achievement', 'Golden Eagle Awar...",", ['Happy Running', 'Rating', '6.4'",", ['Happy Running', 'Rating', '6.4'",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5674,"[['Shanghai', '2018-10-13', 'Mostly cloudy wit...",", ['Shanghai', '2018-10-13', 'Mostly cloudy wi...",", [",", ['Mostly cloudy with northeast winds. The hi...",", ['Chicken\xa0Feet\xa0with\xa0Pickled\xa0Pepp...",", [",", [",", [",", [",", [",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5675,"[['Mi Yang', 'Stars', 'Perfect Two'",", ['Mi Yang', 'Stars', 'Perfect Two'",", [",", ['Mi Yang', 'Achievement', 'Golden Eagle Awa...",", [",", [",", [",", ['Mi Yang', 'Stars', 'Love in The Buff'",", ['Love in The Buff', 'Director', 'Pang Ho-ch...",", ['Love in The Buff', 'Director', 'Pang Ho-ch...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5676,[[,", [",", [",", [",", [",", [",", [",", [",", [",", [",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5677,"[['Leslie Cheung', 'Star sign', 'Virgo'",", ['Leslie Cheung', 'Star sign', 'Virgo'",", [",", ['Leslie Cheung', 'Achievement', 'CNN top fi...",", [",", ['Leslie Cheung', 'Achievement', 'Most Popul...",", [",", ['Leslie Cheung', 'Sings', 'Together We Move...",", [",", [",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 각 feature별 결측치 개수 -- sentence 기준.
> 문장은 있는데 해당 문장에 대한 topic 정보나, type 정보 혹은 knowledge가 없는 경우에 대한 count

In [49]:
feature_na = pd.concat([temp_sentence.count(), temp_sentence.count() - temp_goal_topic.count(),temp_sentence.count() - temp_goal_type.count(),temp_sentence.count() - temp_knowledge.count()],axis=1)
feature_na.columns = ['temp_sentence', 'goal_topic_na', 'goal_type_na', 'knowledge_na' ]
feature_na

    temp_sentence  goal_topic_na  goal_type_na  knowledge_na
0            5678            0.0           0.0           0.0
1            5678            0.0           0.0           0.0
2            5678            0.0           0.0           0.0
3            5678            0.0           0.0           0.0
4            5678            0.0           0.0           0.0
5            5678            0.0           0.0           0.0
6            5678            1.0           1.0           0.0
7            5678            1.0           1.0           0.0
8            5672          448.0         450.0          -5.0
9            5639          418.0         418.0         -38.0
10           5590          674.0         676.0         368.0
11           5513          598.0         599.0         292.0
12           5404          723.0         724.0         490.0
13           5279          601.0         602.0         365.0
14           5151         1769.0        1791.0         470.0
15           5009         1749.0        1771.0         331.0
16           4874         3133.0        3161.0        1513.0
17           4703         3250.0        3269.0        1464.0
18           4473         3705.0        3754.0        2758.0
19           4197         3438.0        3480.0        2763.0
20           3824         3286.0        3350.0        3103.0
21           3410         2912.0        2974.0        2693.0
22           2957         2807.0        2880.0        2482.0
23           2485         2339.0        2410.0        2049.0
24           2097         2032.0        2094.0        2013.0
25           1765         1705.0        1762.0        1687.0
26           1453         1396.0        1452.0        1447.0
27           1191         1157.0        1190.0        1186.0
28            976          957.0           NaN         975.0
29            779          761.0           NaN         778.0
30            626          609.0           NaN           NaN
31            509          492.0           NaN           NaN
32            397          389.0           NaN           NaN
33            301          293.0           NaN           NaN
34            227          222.0           NaN           NaN
35            173          168.0           NaN           NaN
36            130          126.0           NaN           NaN
37             96           92.0           NaN           NaN
38             60            NaN           NaN           NaN
39             42            NaN           NaN           NaN
40             26            NaN           NaN           NaN
41             18            NaN           NaN           NaN
42             14            NaN           NaN           NaN
43             10            NaN           NaN           NaN
44              4            NaN           NaN           NaN
45              3            NaN           NaN           NaN
46              2            NaN           NaN           NaN
47              1            NaN           NaN           NaN
48              1            NaN           NaN           NaN
49              1            NaN           NaN           NaN
50              1            NaN           NaN           NaN

> 각 feature에서 탄생한 dataframe을 stack을 통해 다시 단일 열로 만들어주기.  
> 다만, 이제는 index level을 가진다.

In [50]:
temp_sentence = temp_sentence.stack().to_frame('sentence')
temp_goal_topic = temp_goal_topic.stack().to_frame('goal_topic')
temp_goal_type = temp_goal_type.stack().to_frame('goal_type')
temp_knowledge = temp_knowledge.stack().to_frame('knowledge')

In [51]:
temp_sentence

                                                  sentence
0    0   ['[1] Who is the leading actor of the movie Le...
     1                               "It's Cecilia Cheung"
     2                    'You even know that. Excellent!'
     3    "[2] Thank you for your praise. She's a Chine...
     4                     'Yes my idol is quite unusual.'
...                                                    ...
5677 24                            "I'm glad you like it."
     25                    "[5] It's time to have a dinner
     26                                          goodbye."
     27                                                'OK
     28                                          see ya!']

[130507 rows x 1 columns]

In [52]:
temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")
temp_knowledge.knowledge = temp_knowledge.knowledge.str.strip()
temp_knowledge.knowledge = temp_knowledge.knowledge.str.strip(',')

/tmp/ipykernel_22181/3707197748.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
/tmp/ipykernel_22181/3707197748.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")

In [53]:
temp_sentence

                                                  sentence
0    0    Who is the leading actor of the movie Left Ri...
     1                               "It's Cecilia Cheung"
     2                    'You even know that. Excellent!'
     3    " Thank you for your praise. She's a Chinese ...
     4                     'Yes my idol is quite unusual.'
...                                                    ...
5677 24                            "I'm glad you like it."
     25                       " It's time to have a dinner
     26                                          goodbye."
     27                                                'OK
     28                                          see ya!']

[130507 rows x 1 columns]

> sentence 기준으로 feature 묶어주기.  
> 해당 작업을 통해 각 문장에 해당하는 값들을 간직할 수 있게 된다.

In [54]:
output = pd.concat([temp_sentence,temp_goal_topic,temp_goal_type,temp_knowledge],axis=1)
output = output.reset_index(level=1)
output = output.rename(columns={'level_1':'sentence_index'})
output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))
output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.strip())
output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.strip("'"))
output = output.replace('',np.nan)
output

/tmp/ipykernel_22181/1968960187.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
/tmp/ipykernel_22181/1968960187.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
/tmp/ipykernel_22181/1968960187.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))

,sentence_index,sentence,goal_topic,goal_type,knowledge
0,0,Who is the leading actor of the movie Left Rig...,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,1,It's Cecilia Cheung,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,2,You even know that. Excellent!,Left Right Love Destiny,Q&A,NaN
0,3,Thank you for your praise. She's a Chinese ido...,Cecilia Cheung,Chat about stars,"Cecilia Cheung, Intro, Chinese dreamgirl"
0,4,Yes my idol is quite unusual.,Cecilia Cheung,Chat about stars,NaN
...,...,...,...,...,...
5529,8,NaN,NaN,NaN,NaN
5529,9,NaN,NaN,NaN,NaN
5592,9,NaN,NaN,NaN,NaN
5640,10,NaN,NaN,NaN,NaN
5640,11,NaN,NaN,NaN,NaN

In [55]:
train.drop(columns=['goal','conversation','goal_topic_list','goal_type_list','knowledge'],inplace=True)

In [175]:
# train.situation[train.situation.str.contains('Time')]
temp_situation = train.situation.apply(lambda x:pd.Series(x.split(',')))
temp_situation.columns = ['time','overview']
temp_situation.time = temp_situation.time.str.replace("Time: ","")
# temp_situation[temp_situation['time'].str.contains(r'\d{1,2}:..')]
temp_situation['date'] = temp_situation['time'].str.extract('(\d* \d* - \d* - \d*)')
temp_situation['time'] = temp_situation['time'].str.extract('(\d*:\d)')
temp_situation['topic'] = temp_situation['overview'].str.extract('Topic: (.*)')
temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
wday = temp_situation['overview'].str.extract('( \w*day)')
temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))
temp_situation['wday'] = wday
temp_situation = temp_situation.apply(lambda x:x.str.strip())
temp_situation = temp_situation.rename(columns={'overview':'place'})
temp_situation.date = temp_situation.date.str.replace(' ','')
temp_situation

/tmp/ipykernel_22181/2175856241.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
/tmp/ipykernel_22181/2175856241.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))

      time                 place        date                topic       wday
0     12:0             at school         NaN                  NaN        NaN
1     22:0               at home  2018-12-12                  NaN  Wednesday
2     18:0       on the way home         NaN                  NaN        NaN
3     12:0             at school  2018-11-22                  NaN   Thursday
4     20:0               at home         NaN     Academic setback        NaN
...    ...                   ...         ...                  ...        ...
5673   7:0                   NaN         NaN                  NaN        NaN
5674  22:0               at home  2018-10-13                  NaN   Saturday
5675  20:0               at home         NaN                  NaN        NaN
5676   7:0  on the way to school         NaN  Doing well in exams        NaN
5677  12:0             at school         NaN                  NaN        NaN

[5678 rows x 5 columns]

In [160]:
temp_situation.place.value_counts()

at home                 1828
on the way home          933
on the way to work       686
at work                  672
at school                461
on the way to school     457
Name: overview, dtype: int64

In [162]:
temp_situation.topic.value_counts()

Doing well in exams     158
Academic progress       153
Doing badly in exams    145
Pressure in school      142
Academic setback        139
Easy school work        135
Getting paid            125
Receiving a bonus       125
Promotion               116
Boring work             104
Easy work               102
Busy work                86
Pressure  at work        81
Name: topic, dtype: int64

In [163]:
temp_situation.wday.value_counts()

Monday       237
Sunday       203
Thursday     190
Tuesday      186
Wednesday    184
Saturday     182
Friday       177
Name: wday, dtype: int64

In [192]:
train = pd.concat([train,temp_situation],axis=1)
train.drop(columns=['situation'],inplace=True)
train.reset_index(inplace=True)

In [178]:
train = train.merge(output,left_index=True, right_index=True, how='left')
train

,user_profile_age_range,user_profile_name,user_profile_residence,user_profile_accepted_food,user_profile_accepted_movies,user_profile_accepted_music,user_profile_rejected_music,user_profile_gender,user_profile_accepted_celebrities,user_profile_accepted_movie,...,time,place,date,topic,wday,sentence_index,sentence,goal_topic,goal_type,knowledge
0,Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],...,12:0,at school,NaN,NaN,NaN,0,Who is the leading actor of the movie Left Rig...,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],...,12:0,at school,NaN,NaN,NaN,1,It's Cecilia Cheung,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],...,12:0,at school,NaN,NaN,NaN,2,You even know that. Excellent!,Left Right Love Destiny,Q&A,NaN
0,Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],...,12:0,at school,NaN,NaN,NaN,3,Thank you for your praise. She's a Chinese ido...,Cecilia Cheung,Chat about stars,"Cecilia Cheung, Intro, Chinese dreamgirl"
0,Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",['The Legend of Speed'],...,12:0,at school,NaN,NaN,NaN,4,Yes my idol is quite unusual.,Cecilia Cheung,Chat about stars,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5677,Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,...,12:0,at school,NaN,NaN,NaN,24,I'm glad you like it.,NaN,NaN,NaN
5677,Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,...,12:0,at school,NaN,NaN,NaN,25,It's time to have a dinner,NaN,NaN,NaN
5677,Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,...,12:0,at school,NaN,NaN,NaN,26,goodbye.,NaN,NaN,NaN
5677,Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,...,12:0,at school,NaN,NaN,NaN,27,OK,NaN,NaN,NaN
5677,Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",Running On Karma,...,12:0,at school,NaN,NaN,NaN,28,see ya!,NaN,NaN,NaN

In [ ]:
train.user_profile_

In [1]:
import json, pandas as pd
import numpy as np
dev = pd.read_csv('./data/dev.csv')
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')
def pp(df):
    temp_sentence = df.conversation.apply(lambda x:pd.Series(x.split(',')))
    temp_goal_topic = df.goal_topic_list.apply(lambda x:pd.Series(x.split(',')))
    temp_goal_type = df.goal_type_list.apply(lambda x:pd.Series(x.split(',')))
    temp_knowledge = df.knowledge.apply(lambda x:pd.Series(x.split(']')))
    temp_sentence = temp_sentence.stack().to_frame('sentence')
    temp_goal_topic = temp_goal_topic.stack().to_frame('goal_topic')
    temp_goal_type = temp_goal_type.stack().to_frame('goal_type')
    temp_knowledge = temp_knowledge.stack().to_frame('knowledge')

    temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
    temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")
    temp_knowledge.knowledge = temp_knowledge.knowledge.str.strip()
    temp_knowledge.knowledge = temp_knowledge.knowledge.str.strip(',')
    
    output = pd.concat([temp_sentence,temp_goal_topic,temp_goal_type,temp_knowledge],axis=1)
    output = output.reset_index(level=1)
    output = output.rename(columns={'level_1':'sentence_index'})
    
    output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
    output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
    output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))
    output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.strip())
    output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.strip("'"))
    output = output.replace('',np.nan)
    
    df.drop(columns=['goal','conversation','goal_topic_list','goal_type_list','knowledge'],inplace=True)
    
    temp_situation = df.situation.apply(lambda x:pd.Series(x.split(',')))
    temp_situation.columns = ['time','overview']
    temp_situation.time = temp_situation.time.str.replace("Time: ","")
    
    temp_situation['date'] = temp_situation['time'].str.extract('(\d* \d* - \d* - \d*)')
    temp_situation['time'] = temp_situation['time'].str.extract('(\d*:\d)')
    temp_situation['topic'] = temp_situation['overview'].str.extract('Topic: (.*)')
    temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
    wday = temp_situation['overview'].str.extract('( \w*day)')
    temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))
    temp_situation['wday'] = wday
    temp_situation = temp_situation.apply(lambda x:x.str.strip())
    temp_situation = temp_situation.rename(columns={'overview':'place'})
    temp_situation.date = temp_situation.date.str.replace(' ','')
    df = pd.concat([df,temp_situation],axis=1)
    df.drop(columns=['situation'],inplace=True)
    df.reset_index(inplace=True)
    df = df.merge(output,left_index=True, right_index=True, how='left')
    return df
train = pp(train)
test = pp(test)
dev = pp(dev)
train.to_csv('./data/train_pp.csv',index=False)
test.to_csv('./data/test_pp.csv',index=False)
dev.to_csv('./data/dev_pp.csv',index=False)

/tmp/ipykernel_22895/3850774529.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
/tmp/ipykernel_22895/3850774529.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")
/tmp/ipykernel_22895/3850774529.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
/tmp/ipykernel_22895/3850774529.py:26: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
/tmp/ipykernel_22895/3850774529.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))
/tmp/ipykernel_22895/3850774529.py:41: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
/tmp/ipykernel_22895/3850774529.py:43: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))
/tmp/ipykernel_22895/3850774529.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
/tmp/ipykernel_22895/3850774529.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")
/tmp/ipykernel_22895/3850774529.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
/tmp/ipykernel_22895/3850774529.py:26: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
/tmp/ipykernel_22895/3850774529.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))
/tmp/ipykernel_22895/3850774529.py:41: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
/tmp/ipykernel_22895/3850774529.py:43: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))
/tmp/ipykernel_22895/3850774529.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_sentence.sentence = temp_sentence.sentence.str.replace(r"\[.*\]","")
/tmp/ipykernel_22895/3850774529.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_knowledge.knowledge = temp_knowledge.knowledge.str.replace(r"\'","")
/tmp/ipykernel_22895/3850774529.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\"",""))
/tmp/ipykernel_22895/3850774529.py:26: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\[",""))
/tmp/ipykernel_22895/3850774529.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  output.iloc[:,1:] = output.iloc[:,1:].apply(lambda x:x.str.replace(r"\]",""))
/tmp/ipykernel_22895/3850774529.py:41: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' Topic: .*',''))
/tmp/ipykernel_22895/3850774529.py:43: FutureWarning: The default value of regex will change from True to False in a future version.
  temp_situation = temp_situation.apply(lambda x:x.str.replace(r' \w*day',''))

In [183]:
train.columns

Index(['user_profile_age_range', 'user_profile_name', 'user_profile_residence',
       'user_profile_accepted_food', 'user_profile_accepted_movies',
       'user_profile_accepted_music', 'user_profile_rejected_music',
       'user_profile_gender', 'user_profile_accepted_celebrities',
       'user_profile_accepted_movie', 'user_profile_reject',
       'user_profile_rejected_movies', 'user_profile_occupation',
       'user_profile_accepted_music.1', 'user_profile_accepted_poi',
       'user_profile_favorite_news', 'user_profile_accepted_news',
       'user_profile_poi', 'time', 'place', 'date', 'topic', 'wday',
       'sentence_index', 'sentence', 'goal_topic', 'goal_type', 'knowledge'],
      dtype='object')

In [182]:
test.columns

Index(['user_profile_age_range', 'user_profile_name', 'user_profile_residence',
       'user_profile_accepted_food', 'user_profile_accepted_movies',
       'user_profile_accepted_music', 'user_profile_rejected_music',
       'user_profile_gender', 'user_profile_accepted_celebrities',
       'user_profile_accepted_movie', 'user_profile_reject',
       'user_profile_rejected_movies', 'user_profile_occupation',
       'user_profile_accepted_music.1', 'user_profile_accepted_poi',
       'user_profile_favorite_news', 'user_profile_accepted_news',
       'user_profile_poi', 'time', 'place', 'date', 'topic', 'wday',
       'sentence_index', 'sentence', 'goal_topic', 'goal_type', 'knowledge'],
      dtype='object')

In [54]:
train

,situation,user_profile_age_range,user_profile_name,user_profile_residence,user_profile_accepted_food,user_profile_accepted_movies,user_profile_accepted_music,user_profile_rejected_music,user_profile_gender,user_profile_accepted_celebrities,...,user_profile_occupation,user_profile_accepted_music.1,user_profile_accepted_poi,user_profile_favorite_news,user_profile_accepted_news,user_profile_poi,sentence,goal_topic,goal_type,knowledge
0,"Time: 12:00, at school",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",...,Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN,Who is the leading actor of the movie Left Rig...,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,"Time: 12:00, at school",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",...,Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN,It's Cecilia Cheung,Left Right Love Destiny,Q&A,"Cecilia Cheung, Stars, Left Right Love Destiny"
0,"Time: 12:00, at school",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",...,Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN,You even know that. Excellent!,Left Right Love Destiny,Q&A,
0,"Time: 12:00, at school",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",...,Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN,Thank you for your praise. She's a Chinese ido...,Cecilia Cheung,Chat about stars,"Cecilia Cheung, Intro, Chinese dreamgirl"
0,"Time: 12:00, at school",Under 18 years old,Fangyang Liu,Qingdao,Jiaozi Stuffed with Mackerel,"['Left Right Love Destiny', 'Hot Summer Days',...",['Once'],"[""It's Time""]",Female,"['Cecilia Cheung', 'Kris Wu', 'Nicholas Tse']",...,Student,Time Boils The Rain,['Minguo Seafood Dumpling House'],NaN,NaN,NaN,Yes my idol is quite unusual.,Cecilia Cheung,Chat about stars,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5677,"Time: 12:00, at school",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",...,Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN,I'm glad you like it.,NaN,NaN,NaN
5677,"Time: 12:00, at school",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",...,Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN,It's time to have a dinner,NaN,NaN,NaN
5677,"Time: 12:00, at school",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",...,Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN,goodbye.,NaN,NaN,NaN
5677,"Time: 12:00, at school",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",...,Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN,OK,NaN,NaN,NaN
5677,"Time: 12:00, at school",Under 18 years old,Fangshan Liu,Urumqi,Peanuts with Black Vinegar,['Left Right Love Destiny'],"['The Moon Represents My Heart', 'Run Toward t...","['Silence is Gold', 'A Man Of Intention']",Female,"['Cecilia Cheung', 'Leslie Cheung', 'Nicholas ...",...,Student,['When wind blows again'],NaN,"[""Cecilia Cheung's news"", ""Leslie Cheung's news""]",NaN,NaN,see ya!,NaN,NaN,NaN

In [3]:
train.user_profile_gender.unique()

array(['Female', 'Male'], dtype=object)